services:
  web:
    build:
      context: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app/
      - ./staticfiles:/app/staticfiles
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file:
      - ../.env/dev.env

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/home/app/staticfiles

  dns:
    build:
      dockerfile: ./dns-server/Dockerfile
    restart: always
    ports:
      - 53:53/tcp    
      - 53:53/udp
    volumes:
      - ./dns-server/forward.arpitpatil.com:/etc/bind/forward.arpitpatil.com
      - ./dns-server/reverse.arpitpatil.com:/etc/bind/reverse.arpitpatil.com
      - ./dns-server/named.conf.local:/etc/bind/named.conf.local
      - ./dns-server/named.conf.options:/etc/bind/named.conf.options
    network_mode: host

volumes:
  static_files:
      