services:
  dns:
    build:
      context: .
    restart: always
    ports:
      - 53:53/tcp    
      - 53:53/udp
    volumes:
      - ./forward.arpitpatil.com:/etc/bind/forward.arpitpatil.com
      - ./reverse.arpitpatil.com:/etc/bind/reverse.arpitpatil.com
      - ./named.conf.local:/etc/bind/named.conf.local
      - ./named.conf.options:/etc/bind/named.conf.options
    network_mode: host
    